### ISSUE TITLE
Server Exception on Rejecting Running Task

### ISSUE THREAD

**Issue by rootzoll** [rootzoll/konfetti-app#128]
*** GET Action on Request(31) action(STATE_REJECTED) ***
konfettiApi                | 2017-02-18 17:48:11.214  INFO 1 --- [io-8280-exec-10] d.k.controller.ControllerSecurityHelper  : Check Client Security ...
konfettiApi                | 2017-02-18 17:48:11.214  INFO 1 --- [io-8280-exec-10] d.k.controller.ControllerSecurityHelper  : clientId(110) clientSecret(7c3e0491-c55d-47a2-a97b-29871359dcfc)
konfettiApi                | 2017-02-18 17:48:11.214 DEBUG 1 --- [io-8280-exec-10] de.konfetti.service.ClientServiceImpl    : Client(110) READ
konfettiApi                | 2017-02-18 17:48:11.216  INFO 1 --- [io-8280-exec-10] d.k.controller.ControllerSecurityHelper  : Check Client Security ... OK
konfettiApi                | 2017-02-18 17:48:11.257  INFO 1 --- [io-8280-exec-10] de.konfetti.controller.PartyController   : action request(31) ... client is author(false) partyAdmin(false) partyReview(true)
konfettiApi                | 2017-02-18 17:49:02.270 ERROR 1 --- [io-8280-exec-10] o.h.engine.jdbc.spi.SqlExceptionHelper   : Lock wait timeout exceeded; try restarting transaction
konfettiApi                | 2017-02-18 17:49:02.313 ERROR 1 --- [io-8280-exec-10] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.dao.CannotAcquireLockException: could not execute statement; SQL [n/a]; nested exception is org.hibernate.exception.LockTimeoutException: could not execute statement] with root cause
konfettiApi                |
konfettiApi                | java.sql.SQLException: Lock wait timeout exceeded; try restarting transaction
konfettiApi                | 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055)
konfettiApi                | 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
konfettiApi                | 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491)
konfettiApi                | 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423)
konfettiApi                | 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1936)
konfettiApi                | 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2060)
konfettiApi                | 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2542)
konfettiApi                | 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1734)

**Comment by rootzoll** [comment]
After the team review of the RequestServiceImpl.java I made two different update methods - this should hopefully prevent such exception in the future. closing issue until it is observed again.
