### ISSUE TITLE
new exceptions to check

### ISSUE THREAD

**Issue by rootzoll** [rootzoll/konfetti-app#53]
After the changes on the database with having the level of user like Admin or Reviewer persisted differently I got on error, when loading the party as an admin (working when normal user) 

was not able to reproduce when i started fresh user and promoted to admin  ... maybe this logs are a hint:

```
2016-11-10 10:15:36.043  WARN 1 --- [http-nio-8280-exec-8] de.konfetti.controller.PartyController   : PartyController getAllParties(): TODO: mustHaveParty to add to partylist
2016-11-10 10:15:36.047  INFO 1 --- [http-nio-8280-exec-8] de.konfetti.controller.PartyController   : Was not able to get optional client info on request for party list: result returns more than one elements; nested exception is javax.persistence.NonUniqueResultException: result returns more than one elements
2016-11-10 10:15:36.047  INFO 1 --- [http-nio-8280-exec-8] de.konfetti.controller.PartyController   : RESULT number of parties is 2
2016-11-10 10:15:40.853  INFO 1 --- [pool-2-thread-1] d.k.notifier.NotifierBackgroundTask      : |
```

Also there seems another Exception on the NotifierBackgroundTask after the changes:

```
2016-11-10 10:13:05.854  INFO 1 --- [pool-2-thread-1] d.k.notifier.NotifierBackgroundTask      : Notification seconds(232131) id(9) party(1) user(null) type(REVIEW_WAITING)
2016-11-10 10:13:05.856 ERROR 1 --- [pool-2-thread-1] d.k.notifier.NotifierBackgroundTask      : EXCEPTION on NotifierBackgroundTask loop: 

org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: de.konfetti.data.Party.reviewerUser, could not initialize proxy - no Session
	at org.hibernate.collection.internal.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:587)
	at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:204)
	at org.hibernate.collection.internal.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:566)
	at org.hibernate.collection.internal.AbstractPersistentCollection.read(AbstractPersistentCollection.java:135)
	at org.hibernate.collection.internal.PersistentBag.iterator(PersistentBag.java:277)
	at java.util.AbstractCollection.addAll(AbstractCollection.java:343)
	at de.konfetti.service.UserServiceImpl.getAllUsersReviewerOnParty(UserServiceImpl.java:73)
	at de.konfetti.notifier.NotifierBackgroundTask.shouldNotificationGetHigherAttention(NotifierBackgroundTask.java:202)
	at de.konfetti.notifier.NotifierBackgroundTask.runNotifierBackgroundTaskThread(NotifierBackgroundTask.java:129)
	at de.konfetti.notifier.NotifierBackgroundTask.periodicStartUpTimer(NotifierBackgroundTask.java:101)
	at sun.reflect.GeneratedMethodAccessor137.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

2016-11-10 10:13:10.853  INFO 1 --- [pool-2-thread-1] d.k.notifier.NotifierBackgroundTask      : |
```

**Comment by rootzoll** [comment]
the second exception is looping on logs

**Comment by catarata02** [comment]
should be fixed.. .
